CREATE DATABASE IF NOT EXISTS Escola;
USE Escola;

# DROP TABLE Alunos;
# DROP TABLE Professores;
# DROP TABLE Cursos;
# DROP TABLE Turmas;
# DROP TABLE Disciplinas;
# DROP TABLE Aulas;
# DROP TABLE Matriculas;
# DROP TABLE Presencas;

-- DESIGNER GRAFICO <- TURMAS ->  DESENVOLVIMENTO DE SISTEMAS-- 

CREATE TABLE IF NOT EXISTS Alunos(
	id_alunos INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    cpf INT(2) NOT NULL,
    email VARCHAR(50) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    turma VARCHAR(2) NOT NULL,
    
    UNIQUE (id_alunos, cpf, email, telefone)
);

CREATE TABLE IF NOT EXISTS Professores(
	id_professores INT NOT NULL UNIQUE AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS Cursos(
	id_cursos INT NOT NULL UNIQUE AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS Turmas(
	id_turmas INT NOT NULL UNIQUE AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS Disciplinas(
	id_disciplinas INT NOT NULL UNIQUE AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS Aulas(
	id_aulas INT NOT NULL UNIQUE AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS Matriculas(
	id_matriculas INT NOT NULL UNIQUE AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS Presencas(
	id_presencas INT NOT NULL UNIQUE AUTO_INCREMENT
);